//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FryzjerManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FryzjerManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu HAIRDRESSER 2.0.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adding Customer.
        /// </summary>
        public static string CustomerAddViewName {
            get {
                return ResourceManager.GetString("CustomerAddViewName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add client.
        /// </summary>
        public static string CustomerAddViewNameTitle {
            get {
                return ResourceManager.GetString("CustomerAddViewNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Authors.
        /// </summary>
        public static string CustomersViewAuthorsTitle {
            get {
                return ResourceManager.GetString("CustomersViewAuthorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Customers.
        /// </summary>
        public static string CustomersViewName {
            get {
                return ResourceManager.GetString("CustomersViewName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select all.
        /// </summary>
        public static string ListViewWithCheckboxesSelectAllCheckboxContent {
            get {
                return ResourceManager.GetString("ListViewWithCheckboxesSelectAllCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Main Stock.
        /// </summary>
        public static string MainStockViewName {
            get {
                return ResourceManager.GetString("MainStockViewName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adding Done Service.
        /// </summary>
        public static string ServiceDoneViewName {
            get {
                return ResourceManager.GetString("ServiceDoneViewName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string ViewActualStockButtonSearch {
            get {
                return ResourceManager.GetString("ViewActualStockButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID.
        /// </summary>
        public static string ViewActualStockHeaderID {
            get {
                return ResourceManager.GetString("ViewActualStockHeaderID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string ViewActualStockHeaderName {
            get {
                return ResourceManager.GetString("ViewActualStockHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opened (ml).
        /// </summary>
        public static string ViewActualStockHeaderOpened {
            get {
                return ResourceManager.GetString("ViewActualStockHeaderOpened", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Price.
        /// </summary>
        public static string ViewActualStockHeaderPrice {
            get {
                return ResourceManager.GetString("ViewActualStockHeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Count.
        /// </summary>
        public static string ViewActualStockHeaderUnopened {
            get {
                return ResourceManager.GetString("ViewActualStockHeaderUnopened", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name of searched product:.
        /// </summary>
        public static string ViewActualStockNameOfSearchedProduct {
            get {
                return ResourceManager.GetString("ViewActualStockNameOfSearchedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Actual stock.
        /// </summary>
        public static string ViewActualStockTitle {
            get {
                return ResourceManager.GetString("ViewActualStockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Krzysztof Grzesica.
        /// </summary>
        public static string ViewAuthorsGrzesica {
            get {
                return ResourceManager.GetString("ViewAuthorsGrzesica", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Karolina Prusakowska.
        /// </summary>
        public static string ViewAuthorsPrusakowska {
            get {
                return ResourceManager.GetString("ViewAuthorsPrusakowska", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jakub Wadas.
        /// </summary>
        public static string ViewAuthorsWadas {
            get {
                return ResourceManager.GetString("ViewAuthorsWadas", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Karolina Woźniak.
        /// </summary>
        public static string ViewAuthorsWozniak {
            get {
                return ResourceManager.GetString("ViewAuthorsWozniak", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ADD.
        /// </summary>
        public static string ViewCustomerAddConfirmButtonText {
            get {
                return ResourceManager.GetString("ViewCustomerAddConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name:.
        /// </summary>
        public static string ViewCustomerAddLabelNameContent {
            get {
                return ResourceManager.GetString("ViewCustomerAddLabelNameContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Phone:.
        /// </summary>
        public static string ViewCustomerAddLabelPhoneNumberContent {
            get {
                return ResourceManager.GetString("ViewCustomerAddLabelPhoneNumberContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surname:.
        /// </summary>
        public static string ViewCustomerAddLabelSurnameContent {
            get {
                return ResourceManager.GetString("ViewCustomerAddLabelSurnameContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ADD CUSTOMER.
        /// </summary>
        public static string ViewCustomersAddCustomerButtonText {
            get {
                return ResourceManager.GetString("ViewCustomersAddCustomerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string ViewCustomerSearchButtonSearch {
            get {
                return ResourceManager.GetString("ViewCustomerSearchButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string ViewCustomerSearchHeaderName {
            get {
                return ResourceManager.GetString("ViewCustomerSearchHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Phone.
        /// </summary>
        public static string ViewCustomerSearchHeaderPhone {
            get {
                return ResourceManager.GetString("ViewCustomerSearchHeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surname.
        /// </summary>
        public static string ViewCustomerSearchHeaderSurname {
            get {
                return ResourceManager.GetString("ViewCustomerSearchHeaderSurname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name:.
        /// </summary>
        public static string ViewCustomerSearchLabelImie {
            get {
                return ResourceManager.GetString("ViewCustomerSearchLabelImie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surname:.
        /// </summary>
        public static string ViewCustomerSearchLabelNazwisko {
            get {
                return ResourceManager.GetString("ViewCustomerSearchLabelNazwisko", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search client.
        /// </summary>
        public static string ViewCustomerSearchTitle {
            get {
                return ResourceManager.GetString("ViewCustomerSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SERVICES HISTORY.
        /// </summary>
        public static string ViewCustomersServicesHistoryButtonText {
            get {
                return ResourceManager.GetString("ViewCustomersServicesHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clients.
        /// </summary>
        public static string ViewCustomersTitle {
            get {
                return ResourceManager.GetString("ViewCustomersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu number.
        /// </summary>
        public static string ViewDeliveryAddCount {
            get {
                return ResourceManager.GetString("ViewDeliveryAddCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ml.
        /// </summary>
        public static string VIewDeliveryAddml {
            get {
                return ResourceManager.GetString("VIewDeliveryAddml", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Multi-use products.
        /// </summary>
        public static string ViewDeliveryAddProductsMultiTextBlockText {
            get {
                return ResourceManager.GetString("ViewDeliveryAddProductsMultiTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Single-use products.
        /// </summary>
        public static string ViewDeliveryAddProductsSingleTextBlockText {
            get {
                return ResourceManager.GetString("ViewDeliveryAddProductsSingleTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new product.
        /// </summary>
        public static string ViewDeliveryAddTextNewDelivery {
            get {
                return ResourceManager.GetString("ViewDeliveryAddTextNewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Insert delivery.
        /// </summary>
        public static string ViewDeliveryAddTitle {
            get {
                return ResourceManager.GetString("ViewDeliveryAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ACTUAL STOCK.
        /// </summary>
        public static string ViewMainStockActualStockButtonText {
            get {
                return ResourceManager.GetString("ViewMainStockActualStockButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ADD DELIVERY.
        /// </summary>
        public static string ViewMainStockAddDeliveryButtonText {
            get {
                return ResourceManager.GetString("ViewMainStockAddDeliveryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AUTHORS.
        /// </summary>
        public static string ViewMenuWindowAuthorsButtonText {
            get {
                return ResourceManager.GetString("ViewMenuWindowAuthorsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CUSTOMERS.
        /// </summary>
        public static string ViewMenuWindowCustomersButtonText {
            get {
                return ResourceManager.GetString("ViewMenuWindowCustomersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SERVICES.
        /// </summary>
        public static string ViewMenuWindowServicesButtonText {
            get {
                return ResourceManager.GetString("ViewMenuWindowServicesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu STOCK.
        /// </summary>
        public static string ViewMenuWindowStockButtonText {
            get {
                return ResourceManager.GetString("ViewMenuWindowStockButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Capacity.
        /// </summary>
        public static string ViewNewProductAddCapacityLabelContent {
            get {
                return ResourceManager.GetString("ViewNewProductAddCapacityLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disposable product.
        /// </summary>
        public static string ViewNewProductAddDispProductCheckBoxContent {
            get {
                return ResourceManager.GetString("ViewNewProductAddDispProductCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Price.
        /// </summary>
        public static string ViewNewProductAddPriceLabelContent {
            get {
                return ResourceManager.GetString("ViewNewProductAddPriceLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reusable product.
        /// </summary>
        public static string ViewNewProductAddProductCheckBoxContent {
            get {
                return ResourceManager.GetString("ViewNewProductAddProductCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string ViewProductSearchButtonSearchLabelContent {
            get {
                return ResourceManager.GetString("ViewProductSearchButtonSearchLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name of searched product.
        /// </summary>
        public static string ViewProductSearchNameofProductLabelContent {
            get {
                return ResourceManager.GetString("ViewProductSearchNameofProductLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accept.
        /// </summary>
        public static string ViewServiceDoneAcceptButtonText {
            get {
                return ResourceManager.GetString("ViewServiceDoneAcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount.
        /// </summary>
        public static string ViewServiceDoneAmountLabelContent {
            get {
                return ResourceManager.GetString("ViewServiceDoneAmountLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose.
        /// </summary>
        public static string ViewServiceDoneChooseButtonText {
            get {
                return ResourceManager.GetString("ViewServiceDoneChooseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        public static string ViewServiceDoneDateHeader {
            get {
                return ResourceManager.GetString("ViewServiceDoneDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date of visit:.
        /// </summary>
        public static string ViewServiceDoneDateVisitLabelContent {
            get {
                return ResourceManager.GetString("ViewServiceDoneDateVisitLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Services Done.
        /// </summary>
        public static string ViewServiceDoneDoneServicesLabelContent {
            get {
                return ResourceManager.GetString("ViewServiceDoneDoneServicesLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Client:.
        /// </summary>
        public static string ViewServiceDoneLabelCustomerContent {
            get {
                return ResourceManager.GetString("ViewServiceDoneLabelCustomerContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string ViewServiceDoneNameLabelContent {
            get {
                return ResourceManager.GetString("ViewServiceDoneNameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Visit adding.
        /// </summary>
        public static string ViewServiceDoneTitle {
            get {
                return ResourceManager.GetString("ViewServiceDoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used multi-use products.
        /// </summary>
        public static string ViewServiceDoneUsedProductsMultiTextBlockText {
            get {
                return ResourceManager.GetString("ViewServiceDoneUsedProductsMultiTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used single-use products.
        /// </summary>
        public static string ViewServiceDoneUsedProductsSingleTextBlockText {
            get {
                return ResourceManager.GetString("ViewServiceDoneUsedProductsSingleTextBlockText", resourceCulture);
            }
        }
    }
}
